# Generated by Django 2.1 on 2019-03-10 17:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('models', '0005_auto_20190310_1647'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ride',
            name='price',
            field=models.IntegerField(),
        ),
    ]
