# Generated by Django 2.1 on 2019-03-11 01:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('models', '0006_auto_20190310_1709'),
    ]

    operations = [
        migrations.AlterField(
            model_name='authenticator',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='models.User'),
        ),
        migrations.AlterField(
            model_name='vehicle',
            name='driver',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='models.User'),
        ),
    ]
