services: 
  - docker

sudo: 
  - required

language: python

before_install:
  - docker pull mysql:5.7.23
  - mkdir db
  - docker run --name mysql -d -e MYSQL_ROOT_PASSWORD='$3cureUS' -v ~/db:/var/lib/mysql  mysql:5.7.23
  - sleep 15 
  - docker run -it --name mysql-cmdline --link mysql:db mysql:5.7.23 mysql -uroot -p'$3cureUS' -h db -e "create user 'www'@'%' identified by '\$3cureUS'; create database cs4501 character set utf8; grant all privileges on *.* to 'www'@'%';"
before_script:
  - sleep 5
  - docker ps -a
  - docker-compose up -d
 # - docker run -it --name mysql-cmdline --link mysql:db mysql:5.7.23 mysql -uroot -p'$3cureUS' -h db -e "CREATE USER 'www'@'%' IDENTIFIED BY '$3cureUS'; CREATE DATABASE cs4501 CHARACTER SET utf8; GRANT ALL PRIVILEGES ON *.* TO 'www'@'%';"
  
script: 
  - docker ps -a
  - docker exec models-api bash -c "python manage.py test models"

#after_script: 
#  - docker-compose down
