services: 
  - docker

sudo: 
  - required

language: python

python:
  - "3.5"

before_install:
  - docker pull mysql:5.7.23
  - mkdir db
  - docker run --name mysql -d -e MYSQL_ROOT_PASSWORD='$3cureUS' -v /db:/var/lib/mysql  mysql:5.7.23
  - sleep 20
  - docker run -it --name mysql-cmdline --link mysql:db mysql:5.7.23 mysql -uroot -p'$3cureUS' -h db -e "create user 'www'@'%' identified by '$3cureUS'; create database cs4501 character set utf8; grant all on *.* to 'www'@'%';"

before_script:
  - docker-compose up -d

script: 
  - docker start models-api
  - docker exec models-api bash -c "python manage.py test models"

after_script: 
  - docker-compose down
