services: 
  - docker

sudo: 
  - required

language: python

before_install:
  - docker pull mysql:5.7.23
  - mkdir db
  - docker run --name mysql -d -e MYSQL_ROOT_PASSWORD='/$3cureUS' -v ~/db:/var/lib/mysql  mysql:5.7.23
  - sleep 10
  - docker run -it --name mysql-cmdline --link mysql:db mysql:5.7.23 mysql -uroot -p'/$3cureUS' -h db -e "CREATE USER 'www'@'%' IDENTIFIED BY '/$3cureUS'; CREATE DATABASE cs4501 CHARACTER SET utf8; GRANT ALL PRIVILEGES ON *.* TO 'www'@'%';"
  - sleep 5
  - docker ps -a
  - sleep 5
  - docker start mysql-cmdline
  - sleep 5
  - docker ps -a

before_script:
  - docker start mysql-cmdline
  - docker ps -a
  - sleep 5
  -
  - docker-compose up -d

script: 
  - docker ps -a
  - docker exec models-api bash -c "python manage.py test models"

after_script: 
  - docker-compose down
