models:
  image: tp33/django
  container_name: models-api
  external_links:
    - mysql:db
  volumes:
    - ./models:/app
  ports:
    - "8001:8000"
  deploy:
    resources:
      limits:
      cpu: '0.10'
      memory: 50M
  command: bash -c "python ./manage.py makemigrations models && python ./manage.py migrate models && python manage.py loaddata db.json && mod_wsgi-express start-server --working-directory ./ --reload-on-changes ./models/wsgi.py"

exp:
  image: tp33/django
  container_name: exp-api
  links:
    - models:models-api
   # - es:es
   # - kafka:kafka
  ports:
    - "8002:8000"
  deploy:
    resources:
      limits:
      cpu: '0.10'
      memory: 50M
  volumes:
    - ./experience:/app
  command: "mod_wsgi-express start-server --reload-on-changes ./experience/wsgi.py"

web:
  image: tp33/django
  container_name: web
  links:
    - exp:exp-api
  ports:
    - "8000:8000"
  volumes:
    - ./web:/app
  deploy:
    resources:
      limits:
      cpu: '0.10'
      memory: 50M
  command: "mod_wsgi-express start-server --reload-on-changes ./web/wsgi.py"


# kafka:
#    image: spotify/kafka
#    container_name: kafka
#    environment:
#       ADVERTISED_HOST: kafka
#       ADVERTISED_PORT: 9092  
#    hostname: kafka
   
# es:
#    image: elasticsearch:2.0
#    container_name: es
#    ports:
#       - "9200:9200"

# batch:
#    image: tp33/django
#    container_name: batch
#    links:
#       - kafka:kafka
#       - es:es
#    volumes: 
#       - ./:/app
#    command: bash -c "python batch_script.py"

# selenium-chrome:
#   image: selenium/standalone-chrome
#   container_name: selenium-chrome
#   links:
#     - web:web
#   ports:
#     - "4444:4444"

# selenium-test:
#   image: tp33/django
#   container_name: selenium-test
#   links:
#     - selenium-chrome:selenium-chrome
#     - web:web
#   volumes:
#     - ./selenium:/app
#   command: bash -c "pip install selenium==3.141.0 && python selenium_test.py"
  
#haproxy: 
#  container_name: haproxy
#  image: haproxy
#  ports:
#   - "80:80"
#  links: 
#    - web

# spark-master:
#   image: gettyimages/spark
#   command: bin/spark-class org.apache.spark.deploy.master.Master -h spark-master
#   container_name: spark-master
#   hostname: spark-master
#   environment:
#     MASTER: spark://spark-master:7077
#     SPARK_CONF_DIR: /conf
#   expose:
#     - 7001
#     - 7002
#     - 7003
#     - 7004
#     - 7005
#     - 7006
#     - 7077
#     - 6066
#   ports:
#     - 4040:4040
#     - 6066:6066
#     - 7077:7077
#     - 8080:8080
#   volumes:
#     - ./data:/tmp/data

# spark-worker:
#   image: gettyimages/spark
#   command: bin/spark-class org.apache.spark.deploy.worker.Worker spark://spark-master:7077
#   container_name: spark-worker
#   hostname: spark-worker
#   environment:
#     SPARK_CONF_DIR: /conf
#     SPARK_WORKER_CORES: 2
#     SPARK_WORKER_MEMORY: 512m
#     SPARK_WORKER_PORT: 8881
#     SPARK_WORKER_WEBUI_PORT: 8081
#   links:
#     - spark-master
#   expose:
#     - 7012
#     - 7013
#     - 7014
#     - 7015
#     - 7016
#     - 8881
#   ports:
#     - 8081:8081
#   volumes:
#     - ./data:/tmp/data