models:
  image: tp33/django
  container_name: models-api
  external_links:
    - mysql:db
  volumes:
    - ./models:/app
  ports:
    - "8001:8000"
  command: bash -c "python ./manage.py makemigrations models && python ./manage.py migrate models && python manage.py loaddata db.json && mod_wsgi-express start-server --working-directory ./ --reload-on-changes ./models/wsgi.py"

exp:
  image: tp33/django
  container_name: exp-api
  links:
    - models:models-api
    - es:es
    - kafka:kafka
  ports:
    - "8002:8000"
  volumes:
    - ./experience:/app
  command: "mod_wsgi-express start-server --reload-on-changes ./experience/wsgi.py"

web:
  image: tp33/django
  container_name: web
  links:
    - exp:exp-api
  ports:
    - "8000:8000"
  volumes:
    - ./web:/app
  command: "mod_wsgi-express start-server --reload-on-changes ./web/wsgi.py"


kafka:
   image: spotify/kafka
   container_name: kafka
   environment:
      ADVERTISED_HOST: kafka
      ADVERTISED_PORT: 9092  
   hostname: kafka
   
es:
   image: elasticsearch:2.0
   container_name: es
   ports:
      - "9200:9200"

batch:
   image: tp33/django
   container_name: batch
   links:
      - kafka:kafka
      - es:es
   volumes: 
      - ./:/app
   command: bash -c "python batch_script.py"

selenium-chrome:
  image: selenium/standalone-chrome
  container_name: selenium-chrome
  links:
    - web:web
  ports:
    - "4444:4444"

selenium-test:
  image: tp33/django
  container_name: selenium-test
  links:
    - selenium-chrome:selenium-chrome
    - web:web
  volumes:
    - ./selenium:/app
  #command: bash -c "pip install selenium==<some version number> && python <your_selenium_test_script>.py"
  
haproxy: 
  container_name: haproxy
  image: haproxy
  ports:
   - "80:80"
  links: 
    - web