# Generated by Django 2.1 on 2019-02-05 04:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Hoos_Riding_API', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Vehicle',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('license_plate', models.CharField(max_length=10)),
                ('model', models.CharField(max_length=20)),
                ('color', models.CharField(max_length=15)),
                ('capacity', models.PositiveSmallIntegerField()),
                ('driver', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Hoos_Riding_API.User')),
            ],
        ),
    ]
