# Generated by Django 2.1 on 2019-02-06 00:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Hoos_Riding_API', '0002_vehicle'),
    ]

    operations = [
        migrations.CreateModel(
            name='Ride',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('destination', models.CharField(max_length=50)),
                ('start', models.CharField(max_length=50)),
                ('depart_time', models.CharField(max_length=13)),
                ('passengers', models.ManyToManyField(to='Hoos_Riding_API.User')),
                ('vehicle', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Hoos_Riding_API.Vehicle')),
            ],
        ),
    ]
